/** Declaration file generated by dts-gen */

declare class index {
    constructor(...args: any[]);

    extractColumns(...args: any[]): void;

    log(...args: any[]): void;

}


declare namespace index {
    class LegacyTransportStream {
        constructor(options: any);

        close(): void;

    }

}

